config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals do
    member do
      post :complete
    end
  end
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :content, :user, presence: true
  validates :is_private, :is_complete, inclusion: { in: [true, false] }

  belongs_to :user

  after_initialize :ensure_privacy_defined

  def complete?
    is_complete
  end

  def ensure_privacy_defined
    self.is_private ||= false
  end

  def mark_complete!
    self.is_complete = true
    self.save
  end

  def private?
    is_private
  end

  def public?
    !is_private
  end

  def viewable_by?(other_user)
    other_user == user || public?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  has_many :goals

  attr_reader :password

  after_initialize :ensure_session_token

  def self.find_by_credentials(params)
    user = User.find_by(username: params[:username])
    user && user.is_password?(params[:password]) ? user : nil
  end

  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
    @password = password
  end

  def is_password?(password)
    BCrypt::Password.new(password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = gen_token
    save
    session_token
  end

  def viewable_goals
    Goal.where("user_id = ? OR is_private = false", id)
  end

  def complete_goals(user)
    g = goals.where(is_complete: true)
    user == self ? g : g.where(is_private: false)
  end

  def incomplete_goals(user)
    g = goals.where(is_complete: false)
    user == self ? g : g.where(is_private: false)
  end

  private

  def ensure_session_token
    self.session_token ||= gen_token
  end

  def gen_token
    SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  private

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_user_url unless logged_in?
  end

  def log_in(user)
    session[:session_token] = user.reset_session_token!
  end

  def log_out
    current_user.try(:reset_session_token!)
    session[:session_token] = nil
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :require_login

  def index
    @goals = current_user.viewable_goals.includes(:user)
  end

  def new
    @goal = Goal.new
  end

  def complete
    @goal = Goal.find(params[:id])
    @goal.mark_complete!
    redirect_to @goal
  end

  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def show
    @goal = Goal.find(params[:id])
    if @goal.viewable_by?(current_user)
      render :show
    else
      flash[:errors] = ["Cannot view private goal"]
      redirect_to :index
    end
  end

  def edit
    @goal = Goal.find(params[:id])
    redirect_to @goal if @goal.user != current_user
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to @goal
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to goals_url
  end


  private

  def goal_params
    params.require(:goal).permit(:content, :is_private)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.find_by_credentials(user_params)
    if user
      log_in(user)
      redirect_to goals_url
    else
      @user = User.new(user_params)
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    log_out
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in(@user)
      redirect_to goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    <<-HTM.html_safe
      <input type="hidden"
             name="authenticity_token"
             value="#{form_authenticity_token}">
    HTM
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% action = goal.persisted? ? goal_url(goal) : goals_url %>
<% method = goal.persisted? ? 'patch' : 'post' %>
<% submit_text = goal.persisted? ? 'Update Goal' : 'Add Goal' %>

<form action="<%= action %>" method="post">
  <%= auth_token_input %>
  <input type="hidden" name="_method" value="<%= method %>">
  <label>Goal
    <input type="text" name="goal[content]" value="<%= goal.content %>">
  </label>

  <label>
    <input type="radio" name="goal[is_private]" value="false" checked>
    Public
  </label>

  <label>
    <input type="radio" name="goal[is_private]" value="true">
    Private
  </label>

  <input type="submit" value="<%= submit_text %>">
</form>

app/views/goals/_goal.html.erb
<hr>
<%= goal.user == current_user ? "<em>".html_safe : '' %>
  <h3><%= link_to goal.content, goal %><br>
    <small>
      By: <%= link_to goal.user.username, goal.user %>
      <%= '(private)' if goal.is_private %>
    </small>
  </h3>
<%= goal.user == current_user ? "</em>".html_safe : '' %>

<% if goal.complete? %>
  <p><strong>Completed</strong></p>
<% else %>
  <% if goal.user == current_user %>
    <%= button_to "Complete Goal", complete_goal_url(goal) %>
  <% end %>
  <p><strong>Incomplete</strong></p>
<% end %>

app/views/goals/edit.html.erb
<h2>Edit Goal</h2>

<%= render 'form', goal: @goal %>
<%= link_to "All Goals", goals_url %>

app/views/goals/index.html.erb
<h2>All Goals</h2>
<%= link_to "New Goal", new_goal_url %>
<%= render @goals %>

app/views/goals/new.html.erb
<h2>New Goal</h2>

<%= render 'form', goal: @goal %>
<%= link_to "All Goals", goals_url %>

app/views/goals/show.html.erb
<%= render @goal %>

<% if @goal.user == current_user %>
  <%= link_to "Edit Goal", edit_goal_url(@goal) %>
  <%= button_to "Delete", goal_url(@goal), method: :delete %>
<% end %>

<%= link_to 'Back to Goals', goals_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if logged_in? %>
  <%= current_user.username %>
  <%= button_to 'Log out', session_url, method: :delete %>
<% else %>
  <%= link_to 'Sign in', new_session_url %>
  <%= link_to 'Sign up', new_user_url %>
<% end %>

<%= render 'shared/errors' %>

<%= yield %>

</body>
</html>

app/views/shared/_errors.html.erb
<% if flash[:errors] %>
  <%= flash[:errors].join('<br>').html_safe %>
<% end %>

app/views/users/new.html.erb
<h2>New user</h2>

<form action="<%= users_url %>" method="post">
  <%= auth_token_input %>
  <label>Username
    <input type="text" name="user[username]" value="<%= @user.username %>">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Create User">
</form>

app/views/users/show.html.erb
<h2>Profile</h1>
<%= @user.username %>

<h3>Incomplete</h3>
<%= render @user.incomplete_goals(current_user) %>

<h3>Complete</h3>
<%= render @user.complete_goals(current_user) %>